### ISSUE TITLE
aanpassingen n.a.v. feedback 7 juni 2023

### ISSUE THREAD

**Issue by emshov74** [RoleplayNL/Wetten#1]
### Feedback Wassim Grondbeginselen:
1. [line 11](https://github.com/RoleplayNL/Wetten/blob/122cb94cd0a8898e4eccc26b06dff1ce9e9a164a/docs/index.md?plain=1#L11) aanpassen eis (h-)OvJ naar leidinggevende?;
2. [line 12](https://github.com/RoleplayNL/Wetten/blob/122cb94cd0a8898e4eccc26b06dff1ce9e9a164a/docs/index.md?plain=1#L12) strafmaat naar 120, 120-180 met rechter. Is naar jouw zeggen al rechtgetrokken in art. 28b lid 4 WvSv;
3. [line 20](https://github.com/RoleplayNL/Wetten/blob/122cb94cd0a8898e4eccc26b06dff1ce9e9a164a/docs/index.md?plain=1#L20) komt te vervallen.

### Feedback Wassim overig:
1. [line 89-100 Ambtsinstructie](https://github.com/RoleplayNL/Wetten/blob/122cb94cd0a8898e4eccc26b06dff1ce9e9a164a/docs/ambtsinstructie.md?plain=1#L89) Pepperspray komt te vervallen, of developers/leiding overhalen voor pepperspray;
2. [line 18-34 WvSr](https://github.com/RoleplayNL/Wetten/blob/122cb94cd0a8898e4eccc26b06dff1ce9e9a164a/docs/wetboek-van-strafrecht.md?plain=1#L18) taakstraf wegdoen gezien deze er nog niet is, archiveren voor invoering;
3. [line 18-34 WvSr](https://github.com/RoleplayNL/Wetten/blob/122cb94cd0a8898e4eccc26b06dff1ce9e9a164a/docs/wetboek-van-strafrecht.md?plain=1#L18)Aanpassen structuur lid en sublid, nu is het 1.1.1° maar het moet 1.a.1° zijn (anders koppijn).

### Overige feedback Jim:
1. Geef me perms om te committen ipv dat ik het zo moet doen anders wordt het riot.

**Comment by emshov74** [comment]
Ohja en ook leuk is om een fold-down menu te maken zoals bij verkeerswetgeving bij WvSr en WvSv per titel voor meer overzicht.
![image](https://github.com/RoleplayNL/Wetten/assets/36211362/ee006a0e-be39-4c10-aca6-d604d8ec10b8)

misschien ook voor overige wetten een fold-down menu maken zoals WGVGK

**Comment by Edward-Bakker** [comment]
> 3\. [line 18-34 WvSr](https://github.com/RoleplayNL/Wetten/blob/122cb94cd0a8898e4eccc26b06dff1ce9e9a164a/docs/wetboek-van-strafrecht.md?plain=1#L18)Aanpassen structuur lid en sublid, nu is het 1.1.1° maar het moet 1.a.1° zijn (anders koppijn).

Dit wordt automatisch in markdown verwerkt naar 1.a.1° (zie bijlage)
<img width="392" alt="image" src="https://github.com/RoleplayNL/Wetten/assets/24864616/877c0b57-5c59-4eb2-920c-1db129a24369">
